poprawki - freebsd
git-svn-id: svn+ssh://kadu.net/home/kadu/repos/kadu/trunk@710 fea5205d-6df5-0310-bef7-ea67e47da9a5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4229,7 +4229,7 @@ exec 5>>./config.log
 # pthread
 
 
-echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
+	echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
 echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -4285,19 +4285,74 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_pthread_create" >&5
 echo "${ECHO_T}$ac_cv_lib_pthread_pthread_create" >&6
 if test $ac_cv_lib_pthread_pthread_create = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBPTHREAD 1
-_ACEOF
 
-  LIBS="-lpthread $LIBS"
+		PTHREAD_FLAGS=
+		PTHREAD_LIBS=-lpthread
 
 else
 
-	{ { echo "$as_me:$LINENO: error: libpthread was not found!" >&5
-echo "$as_me: error: libpthread was not found!" >&2;}
+		echo "$as_me:$LINENO: checking if compiler supports -pthread" >&5
+echo $ECHO_N "checking if compiler supports -pthread... $ECHO_C" >&6
+		save_CPPFLAGS="$CPPFLAGS"
+		CPPFLAGS="$CXXFLAGS -pthread"
+		cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+			#include <pthread.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+			pthread_create(0,0,0,0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+			echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+			PTHREAD_FLAGS=-pthread
+			PTHREAD_LIBS=
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+			echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+			{ { echo "$as_me:$LINENO: error: Your system is not supporting pthreads!" >&5
+echo "$as_me: error: Your system is not supporting pthreads!" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+		CPPFLAGS="$save_CPPFLAGS"
+
+fi
+
+
+
 
 
 # QT
@@ -9191,6 +9246,8 @@ s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@CXXCPP@,$CXXCPP,;t t
+s,@PTHREAD_FLAGS@,$PTHREAD_FLAGS,;t t
+s,@PTHREAD_LIBS@,$PTHREAD_LIBS,;t t
 s,@QTMOCDIR@,$QTMOCDIR,;t t
 s,@QTMT@,$QTMT,;t t
 s,@QTLIBDIR@,$QTLIBDIR,;t t
