libpng, libintl
git-svn-id: svn+ssh://kadu.net/home/kadu/repos/kadu/trunk@744 fea5205d-6df5-0310-bef7-ea67e47da9a5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3154,6 +3154,94 @@ fi
 
 
 
+# png
+
+PNG_LIBS="-lpng"
+
+	echo "$as_me:$LINENO: checking if libpng.so library is in system directories" >&5
+echo $ECHO_N "checking if libpng.so library is in system directories... $ECHO_C" >&6
+	save_CPPFLAGS="$CPPFLAGS"
+	CPPFLAGS="$CXXFLAGS -lpng"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+		return 0;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+		CPPFLAGS="$save_CPPFLAGS"
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+		CPPFLAGS="$save_CPPFLAGS"
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+	echo "$as_me:$LINENO: checking for libpng.so in specified directiories" >&5
+echo $ECHO_N "checking for libpng.so in specified directiories... $ECHO_C" >&6
+	FILE_DIR=
+	for dir in /usr/lib /usr/local/lib
+	do
+		if test -f $dir/libpng.so
+		then
+			FILE_DIR=$dir
+			echo "$as_me:$LINENO: result: found in $FILE_DIR" >&5
+echo "${ECHO_T}found in $FILE_DIR" >&6
+
+	PNG_LIBS="$PNG_LIBS -L$FILE_DIR"
+
+			break
+		fi
+	done
+	if test "X$FILE_DIR" = "X"
+	then
+		echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+		if test "X" = "X"
+		then
+			{ { echo "$as_me:$LINENO: error: libpng.so not found!" >&5
+echo "$as_me: error: libpng.so not found!" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+
+	fi
+
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+
+
 # QT
 
 
@@ -5288,8 +5376,8 @@ done
 # gettext
 
 
-	echo "$as_me:$LINENO: checking if libintl.h is in system include dirs" >&5
-echo $ECHO_N "checking if libintl.h is in system include dirs... $ECHO_C" >&6
+	echo "$as_me:$LINENO: checking if libintl.h header is in system directories" >&5
+echo $ECHO_N "checking if libintl.h header is in system directories... $ECHO_C" >&6
 	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -5345,22 +5433,111 @@ echo $ECHO_N "checking for libintl.h in specified directiories... $ECHO_C" >&6
 			FILE_DIR=$dir
 			echo "$as_me:$LINENO: result: found in $FILE_DIR" >&5
 echo "${ECHO_T}found in $FILE_DIR" >&6
+
+	CPPFLAGS="$CPPFLAGS -I$FILE_DIR"
+
 			break
 		fi
 	done
 	if test "X$FILE_DIR" = "X"
 	then
-		{ { echo "$as_me:$LINENO: error: libintl.h not found!" >&5
+		echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+		if test "X" = "X"
+		then
+			{ { echo "$as_me:$LINENO: error: libintl.h not found!" >&5
 echo "$as_me: error: libintl.h not found!" >&2;}
    { (exit 1); exit 1; }; }
+		fi
+
 	fi
-
-
-	CPPFLAGS="$CPPFLAGS -I$FILE_DIR"
 
 
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
+
+
+	echo "$as_me:$LINENO: checking if libintl.so library is in system directories" >&5
+echo $ECHO_N "checking if libintl.so library is in system directories... $ECHO_C" >&6
+	save_CPPFLAGS="$CPPFLAGS"
+	CPPFLAGS="$CXXFLAGS -lintl"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+		return 0;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+		CPPFLAGS="$save_CPPFLAGS"
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+		CPPFLAGS="$save_CPPFLAGS"
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+	echo "$as_me:$LINENO: checking for libintl.so in specified directiories" >&5
+echo $ECHO_N "checking for libintl.so in specified directiories... $ECHO_C" >&6
+	FILE_DIR=
+	for dir in /usr/lib /usr/local/lib
+	do
+		if test -f $dir/libintl.so
+		then
+			FILE_DIR=$dir
+			echo "$as_me:$LINENO: result: found in $FILE_DIR" >&5
+echo "${ECHO_T}found in $FILE_DIR" >&6
+
+	LIBS="$LIBS -L$FILE_DIR"
+
+			break
+		fi
+	done
+	if test "X$FILE_DIR" = "X"
+	then
+		echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+		if test "X " = "X"
+		then
+			{ { echo "$as_me:$LINENO: error: libintl.so not found!" >&5
+echo "$as_me: error: libintl.so not found!" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+
+	fi
+
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 
         MKINSTALLDIRS=
@@ -8119,6 +8296,7 @@ s,@ac_ct_CC@,$ac_ct_CC,;t t
 s,@CCDEPMODE@,$CCDEPMODE,;t t
 s,@PTHREAD_FLAGS@,$PTHREAD_FLAGS,;t t
 s,@PTHREAD_LIBS@,$PTHREAD_LIBS,;t t
+s,@PNG_LIBS@,$PNG_LIBS,;t t
 s,@QTMOCDIR@,$QTMOCDIR,;t t
 s,@QTMT@,$QTMT,;t t
 s,@QTLIBDIR@,$QTLIBDIR,;t t
