nowy mechanizm --with-existing-libgadu
git-svn-id: svn+ssh://kadu.net/home/kadu/repos/kadu/trunk@1724 fea5205d-6df5-0310-bef7-ea67e47da9a5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3380,6 +3380,7 @@ echo $ECHO_N "checking for libpng.so in specified directiories... $ECHO_C" >&6
 	FILE_DIR=
 	for dir in /usr/lib /usr/local/lib
 	do
+		echo DIR: $dir
 		if test -f $dir/libpng.so
 		then
 			FILE_DIR=$dir
@@ -3466,6 +3467,7 @@ echo $ECHO_N "checking for X11/Xlib.h in specified directiories... $ECHO_C" >&6
 	FILE_DIR=
 	for dir in /usr/X11R6/include /usr/include /usr/local/include
 	do
+		echo DIR: $dir
 		if test -f $dir/X11/Xlib.h
 		then
 			FILE_DIR=$dir
@@ -3565,6 +3567,7 @@ echo $ECHO_N "checking for qwidget.h in specified directiories... $ECHO_C" >&6
 	FILE_DIR=
 	for dir in $with_qt_includes $with_qt_dir/include $QTDIR/include /usr/lib/qt/include /usr/lib/qt3/include /usr/local/qt/include /usr/include /usr/include/qt /usr/include/qt3 /usr/local/include /usr/X11R6/include /usr/X11R6/include/qt /usr/X11R6/include/qt3
 	do
+		echo DIR: $dir
 		if test -f $dir/qwidget.h
 		then
 			FILE_DIR=$dir
@@ -3661,6 +3664,7 @@ echo $ECHO_N "checking for libqt-mt.so in specified directiories... $ECHO_C" >&6
 	FILE_DIR=
 	for dir in $with_qt_libs $with_qt_dir/lib $QTDIR/lib /usr/lib/qt3/lib /usr/local/qt/lib /usr/lib/qt /usr/lib /usr/local/lib /usr/X11R6/lib
 	do
+		echo DIR: $dir
 		if test -f $dir/libqt-mt.so
 		then
 			FILE_DIR=$dir
@@ -3708,6 +3712,7 @@ echo $ECHO_N "checking for moc in specified directiories... $ECHO_C" >&6
 	FILE_DIR=
 	for dir in $with_qt_moc $with_qt_dir/bin $QTDIR/bin /usr/lib/qt3/bin /usr/local/qt/bin /usr/lib/qt/bin /usr/bin /bin /usr/local/bin /usr/X11R6/bin
 	do
+		echo DIR: $dir
 		if test -f $dir/moc
 		then
 			FILE_DIR=$dir
@@ -5842,28 +5847,29 @@ fi;
 if test -z "$with_existing_libgadu"; then
 	with_existing_libgadu=no
 fi
-if test "$with_existing_libgadu" = "yes"; then
-	if test "${ac_cv_header_libgadu_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for libgadu.h" >&5
-echo $ECHO_N "checking for libgadu.h... $ECHO_C" >&6
-if test "${ac_cv_header_libgadu_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_libgadu_h" >&5
-echo "${ECHO_T}$ac_cv_header_libgadu_h" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking libgadu.h usability" >&5
-echo $ECHO_N "checking libgadu.h usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
+if test "$with_existing_libgadu" != "no"; then
+
+	echo "$as_me:$LINENO: checking if libgadu.h header is in system directories" >&5
+echo $ECHO_N "checking if libgadu.h header is in system directories... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-$ac_includes_default
-#include <libgadu.h>
+
+		#include <libgadu.h>
+
+int
+main ()
+{
+
+		return 0;
+
+  ;
+  return 0;
+}
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -5877,111 +5883,59 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_header_compiler=yes
+
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_header_compiler=no
+
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+	echo "$as_me:$LINENO: checking for libgadu.h in specified directiories" >&5
+echo $ECHO_N "checking for libgadu.h in specified directiories... $ECHO_C" >&6
+	FILE_DIR=
+	for dir in $with_existing_libgadu $with_existing_libgadu/include
+	do
+		echo DIR: $dir
+		if test -f $dir/libgadu.h
+		then
+			FILE_DIR=$dir
+			echo "$as_me:$LINENO: result: found in $FILE_DIR" >&5
+echo "${ECHO_T}found in $FILE_DIR" >&6
+
+		GADU_INCLUDES="-I$FILE_DIR"
+
+			break
+		fi
+	done
+	if test "X$FILE_DIR" = "X"
+	then
+		echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+		if test "X" = "X"
+		then
+			{ { echo "$as_me:$LINENO: error: libgadu.h not found!" >&5
+echo "$as_me: error: libgadu.h not found!" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+
+	fi
+
+
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
 
-# Is the header present?
-echo "$as_me:$LINENO: checking libgadu.h presence" >&5
-echo $ECHO_N "checking libgadu.h presence... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <libgadu.h>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_c_preproc_warn_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
+	GADU_LIBS=-lgadu
 
-  ac_header_preproc=no
-fi
-rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc in
-  yes:no )
-    { echo "$as_me:$LINENO: WARNING: libgadu.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: libgadu.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: libgadu.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: libgadu.h: proceeding with the preprocessor's result" >&2;}
-    (
-      cat <<\_ASBOX
-## ------------------------------------ ##
-## Report this to bug-autoconf@gnu.org. ##
-## ------------------------------------ ##
-_ASBOX
-    ) |
-      sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-  no:yes )
-    { echo "$as_me:$LINENO: WARNING: libgadu.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: libgadu.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: libgadu.h: check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: libgadu.h: check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: libgadu.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: libgadu.h: proceeding with the preprocessor's result" >&2;}
-    (
-      cat <<\_ASBOX
-## ------------------------------------ ##
-## Report this to bug-autoconf@gnu.org. ##
-## ------------------------------------ ##
-_ASBOX
-    ) |
-      sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-esac
-echo "$as_me:$LINENO: checking for libgadu.h" >&5
-echo $ECHO_N "checking for libgadu.h... $ECHO_C" >&6
-if test "${ac_cv_header_libgadu_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_libgadu_h=$ac_header_preproc
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_libgadu_h" >&5
-echo "${ECHO_T}$ac_cv_header_libgadu_h" >&6
-
-fi
-if test $ac_cv_header_libgadu_h = yes; then
-
-		echo "$as_me:$LINENO: checking for gg_libgadu_version in -lgadu" >&5
-echo $ECHO_N "checking for gg_libgadu_version in -lgadu... $ECHO_C" >&6
-if test "${ac_cv_lib_gadu_gg_libgadu_version+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lgadu $PTHREAD_CPPFLAGS $PTHREAD_LIBS $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
+	echo "$as_me:$LINENO: checking if libgadu.so library is in system directories" >&5
+echo $ECHO_N "checking if libgadu.so library is in system directories... $ECHO_C" >&6
+	save_CFLAGS="$CFLAGS"
+	CFLAGS="$CFLAGS -lgadu"
+	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
@@ -5989,17 +5943,12 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char gg_libgadu_version ();
 int
 main ()
 {
-gg_libgadu_version ();
+
+		return 0;
+
   ;
   return 0;
 }
@@ -6016,40 +5965,53 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_gadu_gg_libgadu_version=yes
+
+		CFLAGS="$save_CFLAGS"
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_gadu_gg_libgadu_version=no
+
+		CFLAGS="$save_CFLAGS"
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+	echo "$as_me:$LINENO: checking for libgadu.so in specified directiories" >&5
+echo $ECHO_N "checking for libgadu.so in specified directiories... $ECHO_C" >&6
+	FILE_DIR=
+	for dir in $with_existing_libgadu $with_existing_libgadu/lib
+	do
+		echo DIR: $dir
+		if test -f $dir/libgadu.so
+		then
+			FILE_DIR=$dir
+			echo "$as_me:$LINENO: result: found in $FILE_DIR" >&5
+echo "${ECHO_T}found in $FILE_DIR" >&6
+
+		GADU_LIBS="$GADU_LIBS -L$FILE_DIR"
+
+			break
+		fi
+	done
+	if test "X$FILE_DIR" = "X"
+	then
+		echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+		if test "X" = "X"
+		then
+			{ { echo "$as_me:$LINENO: error: libgadu.so not found!" >&5
+echo "$as_me: error: libgadu.so not found!" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+
+	fi
+
+
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_gadu_gg_libgadu_version" >&5
-echo "${ECHO_T}$ac_cv_lib_gadu_gg_libgadu_version" >&6
-if test $ac_cv_lib_gadu_gg_libgadu_version = yes; then
-
-			GADU_LIBS=-lgadu
-			GADU_INCLUDES=
-
-else
-
-			{ { echo "$as_me:$LINENO: error: existing libgadu was not found!" >&5
-echo "$as_me: error: existing libgadu was not found!" >&2;}
-   { (exit 1); exit 1; }; }
-
-fi
-
-
-else
-
-		{ { echo "$as_me:$LINENO: error: existing libgadu was not found!" >&5
-echo "$as_me: error: existing libgadu was not found!" >&2;}
-   { (exit 1); exit 1; }; }
-
-fi
-
 
 else
 	MY_SUBDIRS="$MY_SUBDIRS libgadu"
@@ -6431,6 +6393,7 @@ echo $ECHO_N "checking for lib$lib.so in specified directiories... $ECHO_C" >&6
 	FILE_DIR=
 	for dir in $MODULE_LIBS_PATH
 	do
+		echo DIR: $dir
 		if test -f $dir/lib$lib.so
 		then
 			FILE_DIR=$dir
@@ -6514,6 +6477,7 @@ echo $ECHO_N "checking for $hdr in specified directiories... $ECHO_C" >&6
 	FILE_DIR=
 	for dir in $MODULE_INCLUDES_PATH
 	do
+		echo DIR: $dir
 		if test -f $dir/$hdr
 		then
 			FILE_DIR=$dir
