nowe libgadu
git-svn-id: svn+ssh://kadu.net/home/kadu/repos/kadu/trunk@535 fea5205d-6df5-0310-bef7-ea67e47da9a5

diff --git a/libgadu/configure b/libgadu/configure
--- a/libgadu/configure
+++ b/libgadu/configure
@@ -2590,6 +2590,8 @@ echo "${ECHO_T}not found, using reasonable defaults" >&6
 
         stdint_h_foobar=define
 
+
+
     cat > $ac_stdint_h << EOF
 #ifndef __AC_STDINT_H
 #$stdint_h_foobar __AC_STDINT_H 1
@@ -2833,6 +2835,8 @@ install_shared=""
 
 lgadu=""
 
+libgadu_a=""
+
 
 static="static"
 
@@ -2848,6 +2852,8 @@ clean_ekg=""
 distclean_ekg=""
 
 uninstall_ekg=""
+
+dep_ekg=""
 
 
 make_ekgwap=""
@@ -3121,6 +3127,106 @@ fi
 done
 
 
+echo "$as_me:$LINENO: checking for va_copy" >&5
+echo $ECHO_N "checking for va_copy... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <stdarg.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+va_list a, b; va_copy(a, b);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  sed 's/#undef __GG_LIBGADU_HAVE_VA_COPY/#define __GG_LIBGADU_HAVE_VA_COPY/' < lib/libgadu-config.h > lib/libgadu-config.h-
+  mv -f lib/libgadu-config.h- lib/libgadu-config.h
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  sed 's/#undef __GG_LIBGADU_HAVE_VA_COPY.*/\/* & *\//' < lib/libgadu-config.h > lib/libgadu-config.h-
+  mv -f lib/libgadu-config.h- lib/libgadu-config.h
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+echo "$as_me:$LINENO: checking for __va_copy" >&5
+echo $ECHO_N "checking for __va_copy... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <stdarg.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+va_list a, b; __va_copy(a, b);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  sed 's/#undef __GG_LIBGADU_HAVE___VA_COPY/#define __GG_LIBGADU_HAVE___VA_COPY/' < lib/libgadu-config.h > lib/libgadu-config.h-
+  mv -f lib/libgadu-config.h- lib/libgadu-config.h
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  sed 's/#undef __GG_LIBGADU_HAVE___VA_COPY.*/\/* & *\//' < lib/libgadu-config.h > lib/libgadu-config.h-
+  mv -f lib/libgadu-config.h- lib/libgadu-config.h
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
 # jak± wersjê libgadu kompilujemy?
 
 # Check whether --enable-shared or --disable-shared was given.
@@ -3193,19 +3299,27 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
+
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_C99_VSNPRINTF 1
 _ACEOF
 
-  echo "$as_me:$LINENO: result: yes" >&5
+	echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+      	sed 's/#undef __GG_LIBGADU_HAVE_C99_VSNPRINTF/#define __GG_LIBGADU_HAVE_C99_VSNPRINTF/' < lib/libgadu-config.h > lib/libgadu-config.h-
+        mv -f lib/libgadu-config.h- lib/libgadu-config.h
+
 else
   echo "$as_me: program exited with status $ac_status" >&5
 echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
 ( exit $ac_status )
-echo "$as_me:$LINENO: result: no" >&5
+
+	echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+        sed 's/#undef __GG_LIBGADU_HAVE_C99_VSNPRINTF/\/* & *\//' < lib/libgadu-config.h > lib/libgadu-config.h-
+        mv -f lib/libgadu-config.h- lib/libgadu-config.h
+
 fi
 rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
@@ -4194,6 +4308,7 @@ s,@install_ioctld@,$install_ioctld,;t t
 s,@shared@,$shared,;t t
 s,@install_shared@,$install_shared,;t t
 s,@lgadu@,$lgadu,;t t
+s,@libgadu_a@,$libgadu_a,;t t
 s,@static@,$static,;t t
 s,@install_static@,$install_static,;t t
 s,@ekg@,$ekg,;t t
@@ -4201,6 +4316,7 @@ s,@install_ekg@,$install_ekg,;t t
 s,@clean_ekg@,$clean_ekg,;t t
 s,@distclean_ekg@,$distclean_ekg,;t t
 s,@uninstall_ekg@,$uninstall_ekg,;t t
+s,@dep_ekg@,$dep_ekg,;t t
 s,@make_ekgwap@,$make_ekgwap,;t t
 s,@install_ekgwap@,$install_ekgwap,;t t
 s,@OBJS@,$OBJS,;t t
