ostrzeżenia + autopatching gdy katalog jest pusty
git-svn-id: svn+ssh://kadu.net/home/kadu/repos/kadu/trunk@3547 fea5205d-6df5-0310-bef7-ea67e47da9a5

diff --git a/varia/scripts/autodownload b/varia/scripts/autodownload
--- a/varia/scripts/autodownload
+++ b/varia/scripts/autodownload
@@ -22,7 +22,7 @@ fi
 KADU_VERSION=`echo $KADU_VERSION | sed s/-.*//`
 
 ITEM_WEBSITES=`cat $1.web`
-if test -z $ITEM_WEBSITES; then
+if test -z "$ITEM_WEBSITES"; then
 	echo -e "\033[31m!!!\033[0m ERROR: Homepage for $1 $2 is unknown"
 	echo
 	exit 1
@@ -35,7 +35,7 @@ for ITEM_WEBSITE in $ITEM_WEBSITES; do
 		break
 	fi
 done
-if test -z $ITEM_HREFS; then
+if test -z "$ITEM_HREFS"; then
 	echo -e "\033[31m!!!\033[0m ERROR: Downloading of $1 $2 href-file failed"
 	echo
 	exit 1
@@ -47,7 +47,7 @@ for ITEM_HREF in $ITEM_HREFS; do
 		break
 	fi
 done
-if test -z $ITEM_HREF_NAME; then
+if test -z "$ITEM_HREF_NAME"; then
 	echo -e "\033[31m!!!\033[0m ERROR: Downloading of $1 $2 package failed"
 	echo
 	exit 1
@@ -91,12 +91,14 @@ if [ -d patches/$1 ]; then
 	echo -e "\033[32m>>>\033[0m Patching $1 $2"
 	echo
 	for i in patches/$1/*; do
-		patch -f -p0 --dry-run -s < $i
-		if [ $? -ne 0 ]; then
-			echo -e "\033[31m!!!\033[0m ERROR: Patching module $1 with file $i failed"
-			exit 1
-		else
-			patch -f -p0 < $i
+		if [ -f $i ]; then
+			patch -f -p0 --dry-run -s < $i
+			if [ $? -ne 0 ]; then
+				echo -e "\033[31m!!!\033[0m ERROR: Patching module $1 with file $i failed"
+				exit 1
+			else
+				patch -f -p0 < $i
+			fi
 		fi
 	done
 fi
