automatyczne patchowanie zewnętrznych modułów
git-svn-id: svn+ssh://kadu.net/home/kadu/repos/kadu/trunk@3533 fea5205d-6df5-0310-bef7-ea67e47da9a5

diff --git a/varia/scripts/autodownload b/varia/scripts/autodownload
--- a/varia/scripts/autodownload
+++ b/varia/scripts/autodownload
@@ -83,7 +83,24 @@ if ! test -d "$1"; then
 		exit 1
 	fi
 fi
+
 touch $1/.autodownloaded
+
+if [ -d patches/$1 ]; then
+	echo
+	echo -e "\033[32m>>>\033[0m Patching $1 $2"
+	echo
+	for i in patches/$1/*; do
+		patch -f -p0 --dry-run -s < $i
+		if [ $? -ne 0 ]; then
+			echo -e "\033[31m!!!\033[0m ERROR: Patching module $1 with file $i failed"
+			exit 1
+		else
+			patch -f -p0 < $i
+		fi
+	done
+fi
+
 
 echo -e "\033[32m>>>\033[0m $2 downloaded and unpacked successfully"
 echo
